language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-machinepack' ]; then cd .. && eval "mv $currentfolder generator-machinepack" && cd generator-machinepack; fi
